apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql    # Update the selector to match the labels of your MySQL pods
  ports:
    - protocol: TCP
      port: 3306   # Update the port to match the MySQL port
      targetPort: 3306

